/**
 * wordBank.js
 * ─────────────────────────────────────────────────────────────────────────────
 * Curated word list for the Smart Password Generator.
 * Words are chosen for: memorability, length (4–10 chars), zero dict-attack
 * risk when combined (the combination is unpredictable, not the words alone).
 *
 * All words are Title-cased so the generator can lowercase/uppercase freely.
 *
 * Coverage: every letter A–Z has at least 4 representatives so the
 * letter-pivot anchor system always finds a word regardless of the user's
 * first name, pet name, etc.
 * ─────────────────────────────────────────────────────────────────────────────
 */

export const WORD_BANK = {
  tech: [
    // A-Z coverage within tech
    'Algorithm', 'Async',
    'Binary', 'Buffer', 'Beacon',
    'Cache', 'Cipher', 'Cluster', 'Codec',
    'Daemon', 'Deploy',
    'Endpoint',
    'Fiber', 'Firewall', 'Forge',
    'Gateway',
    'Hotfix',
    'Index',
    'Kernel',
    'Lambda', 'Latency',
    'Matrix', 'Module',
    'Nexus', 'Network',
    'Offset',
    'Packet', 'Pixel', 'Proxy',
    'Queue',
    'Relay', 'Runtime',
    'Signal', 'Socket', 'Stream', 'Switch', 'Shader', 'Syntax',
    'Tensor', 'Token',
    'Uplink', 'Upload',
    'Vector', 'Vertex',
    'Webhook',
    'Xunit',
    'Yield',
    'Zlib',
  ],

  space: [
    'Andromeda', 'Apogee', 'Aurora',
    'Binary',
    'Cassini', 'Comet', 'Cosmos',
    'Eclipse', 'Equinox',
    'Fusion',
    'Galaxy',
    'Helios', 'Horizon',
    'Interstellar',
    'Jupiter',
    'Kepler',
    'Lunar',
    'Meteor', 'Milky',
    'Nebula', 'Nova',
    'Orbit',
    'Perseid', 'Photon', 'Pioneer', 'Polaris', 'Pulsar',
    'Quasar',
    'Solaris', 'Stellar',
    'Titan',
    'Umbra',
    'Vortex', 'Voyager',
    'Wormhole',
    'Xenon',
    'Zenith',
  ],

  nature: [
    'Amber', 'Alpine',
    'Basalt', 'Blizzard',
    'Canyon', 'Cascade', 'Cavern', 'Cobalt', 'Crimson',
    'Delta', 'Dune',
    'Estuary', 'Ember',
    'Fjord', 'Frost',
    'Geyser', 'Glacier', 'Granite',
    'Highland',
    'Iceberg',
    'Jungle',
    'Kelp',
    'Lagoon',
    'Mantle', 'Marsh',
    'Obsidian',
    'Plateau',
    'Quartz',
    'Ravine', 'Ridge',
    'Savanna', 'Summit', 'Serene',
    'Tundra', 'Torrent',
    'Upland',
    'Valley',
    'Wetland',
    'Xeric',
    'Yarrow',
    'Zircon',
  ],

  animals: [
    'Albatross',
    'Badger', 'Bison',
    'Cobra', 'Condor', 'Cougar', 'Crane',
    'Dingo',
    'Eagle',
    'Falcon', 'Ferret',
    'Griffin',
    'Harrier',
    'Ibis',
    'Jaguar',
    'Kestrel',
    'Lynx', 'Leopard',
    'Mamba', 'Marlin', 'Mantis',
    'Narwhal',
    'Ocelot', 'Osprey', 'Otter',
    'Panther', 'Pelican', 'Python',
    'Quetzal',
    'Raven', 'Rhino',
    'Stallion', 'Stag',
    'Tiger', 'Tapir',
    'Urubu',
    'Viper',
    'Wolverine',
    'Xerus',
    'Yak',
    'Zorilla',
  ],

  science: [
    'Alloy',
    'Baryon',
    'Carbon', 'Catalyst', 'Cortex',
    'Diffuse',
    'Entropy', 'Enzyme',
    'Fission', 'Fusion',
    'Genome',
    'Helium', 'Helix',
    'Inertia', 'Isotope',
    'Kinetic',
    'Lithium',
    'Neuron', 'Neutron',
    'Osmosis',
    'Plasma', 'Polymer', 'Proton',
    'Quantum',
    'Resonant', 'Refract',
    'Synapse',
    'Thermal',
    'Uranium',
    'Valence', 'Voltage',
    'Waveform',
    'Xenolith',
    'Yttrium',
    'Zeolite',
  ],

  fantasy: [
    'Aether', 'Aegis', 'Arcane',
    'Bastion', 'Banshee',
    'Citadel', 'Chimera',
    'Dragon',
    'Ember',
    'Frost',
    'Grimoire', 'Golem',
    'Hydra',
    'Illusion',
    'Joust',
    'Kraken',
    'Lore',
    'Mystic', 'Magus',
    'Nexus',
    'Oracle',
    'Phantom',
    'Quest',
    'Relic', 'Rune',
    'Seraph', 'Shadow', 'Specter', 'Shard',
    'Tempest', 'Titan',
    'Undying',
    'Vortex',
    'Wraith',
    'Xylem',
    'Yokai',
    'Zealot',
  ],

  general: [
    'Agile', 'Apex',
    'Bold', 'Brave', 'Blaze',
    'Core', 'Crest',
    'Dash',
    'Edge',
    'Fleet', 'Firm',
    'Guard',
    'Honor',
    'Iron',
    'Juggernaut',
    'Keen',
    'Lean',
    'Nimble',
    'Orbit',
    'Prime', 'Pure',
    'Quest',
    'Rapid', 'Rocket',
    'Solid', 'Stark', 'Stealth', 'Strike', 'Surge', 'Swift', 'Sharp',
    'Turbo',
    'Ultra',
    'Vivid', 'Volt',
    'Willful',
    'Xcel',
    'Yield',
    'Zenith',
  ],
};

/** All words flattened into a single deduplicated array. */
export const ALL_WORDS = [...new Set(Object.values(WORD_BANK).flat())];

/** Category names for the UI selector. */
export const CATEGORIES = Object.keys(WORD_BANK);
